// LOCALHOST
### Get all teams
GET http://localhost:8080/teams

### Get team by id
GET http://localhost:8080/teams/6472a84640e8e6df94d5896c

### Create team
POST http://localhost:8080/teams HTTP/1.1
content-type: application/json

{
    "teamName": "Titans",
    "location": "Tennessee",
    "stadiumName": "Nissan Stadium",
    "yearEstablished": "1959",
    "numberChampionships": "0"
}


### PUT team
PUT http://localhost:8080/teams/6472a85d40e8e6df94d58970 HTTP/1.1
content-type: application/json

{
    "teamName": "JAGS",
    "location": "Jacksonville",
    "stadiumName": "TIAA Bank Field",
    "yearEstablished": "1995",
    "numberChampionships": "0"
}

### DELETE team
DELETE http://localhost:8080/teams/6474d6e7f819fe8f3236a002 HTTP/1.1

---------------------------------------------------------------------------------

// PRODUCTION Deploy
### Get all teams
GET https://zr-weeks5-8.onrender.com/teams

### Get team by id
GET https://zr-weeks5-8.onrender.com/teams/6472a84640e8e6df94d5896c



### Create team
POST https://zr-weeks5-8.onrender.com/teams HTTP/1.1
content-type: application/json

{
    "teamName": "Titans",
    "location": "Tennessee",
    "stadiumName": "Nissan Stadium",
    "yearEstablished": "1959",
    "numberChampionships": "0"
}


### PUT team
PUT https://zr-weeks5-8.onrender.com/teams/6472a85d40e8e6df94d58970 HTTP/1.1
content-type: application/json

{
    "teamName": "JAGS",
    "location": "Jacksonville",
    "stadiumName": "TIAA Bank Field",
    "yearEstablished": "1995",
    "numberChampionships": "0"
}

### DELETE team
DELETE https://zr-weeks5-8.onrender.com/teams HTTP/1.1