// LOCALHOST
### Get all teams
GET http://localhost:8080/teams

### Get team by teamName
GET http://localhost:8080/teams/Steelers

### Create team
POST http://localhost:8080/teams HTTP/1.1
content-type: application/json

{
    "teamName": "Titans",
    "location": "Tennessee",
    "stadiumName": "Nissan Stadium",
    "yearEstablished": "1959",
    "numberChampionships": "0"
}


### PUT team
PUT http://localhost:8080/teams/Jaguars HTTP/1.1
content-type: application/json

{
    "teamName": "Jaguars",
    "location": "Jacksonville",
    "stadiumName": "TIAA Bank Field",
    "yearEstablished": "1995",
    "numberChampionships": "0"
}

### DELETE team
DELETE http://localhost:8080/teams/Titans HTTP/1.1

---------------------------------------------------------------------------------

// PRODUCTION Deploy
### Get all teams
GET https://zr-weeks5-8.onrender.com/teams

### Get team by teamName
GET https://zr-weeks5-8.onrender.com/teams/Steelers



### Create team
POST https://zr-weeks5-8.onrender.com/teams HTTP/1.1
content-type: application/json

{
    "teamName": "Titans",
    "location": "Tennessee",
    "stadiumName": "Nissan Stadium",
    "yearEstablished": "1959",
    "numberChampionships": "0"
}


### PUT team
PUT https://zr-weeks5-8.onrender.com/teams/Jaguars HTTP/1.1
content-type: application/json

{
    "teamName": "Jaguars",
    "location": "Jacksonville",
    "stadiumName": "TIAA Bank Field",
    "yearEstablished": "1995",
    "numberChampionships": "0"
}

### DELETE team
DELETE https://zr-weeks5-8.onrender.com/teams/Titans HTTP/1.1